version: '3.7'

services:
  backend:
    build:
      context: ./BackendApi
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - database

  database:
    build:
      context: ./Database
      dockerfile: Dockerfile
    networks:
      - app-network

  httpd:
    build:
      context: ./HTTPServer
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network: